// Generated by scripts/codegen.mjs from src/sections/<name>/section.meta.json.
// Do not hand-edit between the markers — re-run codegen instead.
// BEGIN GENERATED SECTION IMPORTS
// END GENERATED SECTION IMPORTS

export default function Home() {
  return (
    <main className="flex min-h-screen items-center justify-center">
      <p className="text-muted-foreground">
        Clone target not yet built. Run <code className="font-mono text-foreground">/clone-website</code> to start.
      </p>
      {/* BEGIN GENERATED SECTIONS */}
      {/* END GENERATED SECTIONS */}
    </main>
  );
}
